In [4]:
%config Completer.use_jedi = False

In [8]:
import pandas as pd

In [17]:
df = pd.read_csv('./data/gapminder.tsv', sep='\t')

In [18]:
df.head()

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [19]:
df.columns

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

In [22]:
df.index

RangeIndex(start=0, stop=1704, step=1)

In [23]:
df.values

array([['Afghanistan', 'Asia', 1952, 28.801, 8425333, 779.4453145],
       ['Afghanistan', 'Asia', 1957, 30.332, 9240934, 820.8530296],
       ['Afghanistan', 'Asia', 1962, 31.997, 10267083, 853.10071],
       ...,
       ['Zimbabwe', 'Africa', 1997, 46.809, 11404948, 792.4499603],
       ['Zimbabwe', 'Africa', 2002, 39.989, 11926563, 672.0386227],
       ['Zimbabwe', 'Africa', 2007, 43.487, 12311143, 469.7092981]],
      dtype=object)

In [24]:
#how to know what the type of your objects are, this means pandas dataframe object
type(df)

pandas.core.frame.DataFrame

In [26]:
#gives you the number of rows and columns of your dataset
df.shape

(1704, 6)

In [27]:
#this is useful if you dont have many columns to findout your DF info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   object
 1   continent  1704 non-null   object
 2   year       1704 non-null   int64
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB

In [31]:
country_df= df['country']

In [32]:
country_df.head()

0    Afghanistan
1    Afghanistan
2    Afghanistan
3    Afghanistan
4    Afghanistan
Name: country, dtype: object

In [33]:
#dataframe is called as a bunch of columns, each column is called Series
type(country_df)

pandas.core.series.Series

In [35]:
#if you to subset multiple things or in this context columns, you need to use list which is 2 square brackets
subset = df[['country','continent','year']]

In [36]:
subset.head()

       country continent  year
0  Afghanistan      Asia  1952
1  Afghanistan      Asia  1957
2  Afghanistan      Asia  1962
3  Afghanistan      Asia  1967
4  Afghanistan      Asia  1972

In [38]:
pd.__version__

'1.2.4'

In [40]:
#how to subset rows, using this function will get you the character '2' the dataset above from row number column, not really the index 2, its more like character matching which said i'm located/looking character 2
#df.loc[[2,0]]

#different than loc, this iloc means indexloc, this function really looking right at the index 2 not the character for 2 
df.iloc[2]

country      Afghanistan
continent           Asia
year                1962
lifeExp           31.997
pop             10267083
gdpPercap      853.10071
Name: 2, dtype: object

In [45]:
subsetrow = df.loc[:,['year','pop']]

In [44]:
subsetrow.head()

   year       pop
0  1952   8425333
1  1957   9240934
2  1962  10267083
3  1967  11537966
4  1972  13079460

In [50]:
df.loc[df['year'] ==1967,['country','pop']]

                 country       pop
3            Afghanistan  11537966
15               Albania   1984060
27               Algeria  12760499
39                Angola   5247469
51             Argentina  22934225
...                  ...       ...
1647             Vietnam  39463910
1659  West Bank and Gaza   1142636
1671         Yemen, Rep.   6740785
1683              Zambia   3900000
1695            Zimbabwe   4995432

[142 rows x 2 columns]

In [58]:
df.loc[(df['year'] ==1967) & (df['pop'] >=10_000_000) ,['country','pop']]

               country        pop
3          Afghanistan   11537966
27             Algeria   12760499
51           Argentina   22934225
63           Australia   11872264
99          Bangladesh   62821884
171             Brazil   88049823
243             Canada   20819767
291              China  754550000
303           Colombia   19764027
327   Congo, Dem. Rep.   19941073
459              Egypt   31681188
507           Ethiopia   27860297
531             France   49569000
567            Germany   76368453
675            Hungary   10223422
699              India  506000000
711          Indonesia  109343000
723               Iran   26538000
771              Italy   52667100
795              Japan  100825279
819              Kenya   10191512
831   Korea, Dem. Rep.   12617009
843        Korea, Rep.   30131000
939           Malaysia   10154878
987             Mexico   47995559
1023           Morocco   14770296
1047           Myanmar   25870271
1071             Nepal   11261690
1083       Netherlands   12596822
1131           Nigeria   47287752
1167          Pakistan   60641899
1203              Peru   12132200
1215       Philippines   35356600
1227            Poland   31785378
1275           Romania   19284814
1407      South Africa   20997321
1419             Spain   32850275
1431         Sri Lanka   11737396
1443             Sudan   12716129
1503            Taiwan   13648692
1515          Tanzania   12607312
1527          Thailand   34024249
1575            Turkey   33411317
1599    United Kingdom   54959000
1611     United States  198712000
1647           Vietnam   39463910