### Loading Data Into Pandas

In [29]:
import pandas as pd

#poke = pd.read_csv('Pokemon_data.csv')

# poke_xlsx = pd.read.excel('pokemon.xlsx')
poke_text = pd.read_csv('university_towns.txt', delimiter='\n')

#print(poke_text.head(10))
poke_text.head(20)

                                        Alabama[edit]
0                       Auburn (Auburn University)[1]
1              Florence (University of North Alabama)
2     Jacksonville (Jacksonville State University)[2]
3          Livingston (University of West Alabama)[2]
4            Montevallo (University of Montevallo)[2]
5                           Troy (Troy University)[2]
6   Tuscaloosa (University of Alabama, Stillman Co...
7                   Tuskegee (Tuskegee University)[5]
8                                        Alaska[edit]
9       Fairbanks (University of Alaska Fairbanks)[2]
10                                      Arizona[edit]
11         Flagstaff (Northern Arizona University)[6]
12                   Tempe (Arizona State University)
13                     Tucson (University of Arizona)
14                                     Arkansas[edit]
15  Arkadelphia (Henderson State University, Ouach...
16  Conway (Central Baptist College, Hendrix Colle...
17           Fayetteville (University of Arkansas)[7]
18           Jonesboro (Arkansas State University)[8]
19         Magnolia (Southern Arkansas University)[2]

### Reading data in Pandas

In [9]:
 ## Read Headers
#print(poke.columns)

## Read each column
#print(poke[['Name','Type 1','Attack']][0:5])

## Read Each Row
#print(poke.iloc[0:4])

#for index, row in poke.iterrows():
#    print(index, row['Name'])

poke.loc[poke['HP'] == 39]

## Read a specific location (R,C)
#print(poke.iloc[2,1])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,2,False,309

### Sorting/Describing Data

In [4]:
#poke.sort_values(['HP','Attack'], ascending=[1,1])
#poke.describe()
poke

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

### Making Changes to the Data

In [5]:
#this is for making a Total column 
#poke['Total'] = poke['HP'] + poke['Attack'] + poke['Defense'] + poke['Sp. Atk'] + poke['Sp. Def'] + poke['Speed']

#this is for deleting Total column
#poke = poke.drop(columns=['Total'])

#this is for making Total column with sum(perjumlahan) dari index 4 sampai 10
poke['Total'] = poke.iloc[:,4:10].sum(axis=1)

#this is for changing the place for Total column with viewing the data
#cols = list(poke.columns.values)
#poke = poke[cols[0:4] +[cols[-1]]+ cols[4:12]]

poke.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

### Saving our Data (Exporting into Desired Format)

In [6]:
#poke.to_csv('modified.csv')
#poke.to_excel('modified.xlsx', index=False)
#poke.to_csv('modified.txt', index=False, sep='\t')

### Filtering Data

In [7]:
# poke.loc[poke['Type 1']=='Grass']
import re

#this is for locate Type 1 Column with Grass value and Type 2 column with Poison Value and HP column with value more than 70
#new_poke = poke.loc[(poke['Type 1']=='Grass') & (poke['Type 2']=='Poison') &(poke['HP'] > 70)]
#new_poke

# new_poke.to_csv('filtered.csv')
#this is to loc string values in Name columns which contain Mega
#poke.loc[(poke['Name'].str.contains('Mega')) & (poke['Type 1']=='Fire')]
#poke.loc[poke['Type 1'].str.contains('Fire|Grass', regex=True)]

#to get all values in column Name with the beginning of String with PI
poke.loc[poke['Name'].str.contains('^pi[a-z]*',flags=re.I, regex=True)]


#this is to loc string values in Name columns which do not contain Mega
#poke.loc[~poke['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False,251
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False,349
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False,479
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False,579
30,25,Pikachu,Electric,NaN,35,55,40,50,50,90,1,False,320
136,127,Pinsir,Bug,NaN,65,125,100,55,70,85,1,False,500
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False,600
186,172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False,205
219,204,Pineco,Bug,NaN,50,65,90,35,35,15,2,False,290
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False,450
438,393,Piplup,Water,NaN,53,51,53,61,56,40,4,False,314
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False,418
578,519,Pidove,Normal,Flying,50,55,50,36,30,43,5,False,264

In [8]:
# if you want to reset the index after filtering some data, drop=True for deleting the former index, and inplace=True is to save the change into the new_poke when you dont need to reset into a new dataframe to conserve a little bit memory
# new_poke = new_poke.reset_index(drop=True, inplace=True)
new_poke.reset_index(drop=True, inplace=True)
new_poke

NameError: name 'new_poke' is not defined

Conditional Changes

In [ ]:
#changing Fire value in Type 1 column itu Flamer
#poke.loc[poke['Type 1']== 'Fire', 'Type 1'] = 'Flamer'
#poke.loc[poke['Type 1']== 'Flamer', 'Type 1'] = 'Fire'

#to change the value in Legendary column into True if the type is Fire
#poke.loc[poke['Type 1'] == 'Fire', 'Legendary'] = True

#to change the value in multiple column at the same time
#poke.loc[poke['Total']> 500,['Generation','Legendary']] = ['Test2','Test1']

poke

In [ ]:
#to re load the data before change the legendary column value
poke = pd.read_csv('modified.csv')
poke

### Aggregate Statistics (Groupby)

In [ ]:
#Untuk Melihat nilai rata-rata dari setiap nilai ni kolum Type 1
#poke.groupby(['Type 1']).mean().sort_values('Attack', ascending=False)

poke['count'] = 1
#poke.groupby(['Type 1']).count()['count']
poke.groupby(['Type 1','Type 2']).count()['count']

### Working with large amounts of data

In [ ]:
#pass in data with 5rows at a time according to the number of ChunkSize
#for poke in pd.read_csv('modified.csv', chunksize=5):
   # print("CHUNK DF")
    #print(poke)

new_poke = pd.DataFrame(columns=poke.columns)
for poke in pd.read_csv('modified.csv', chunksize=3):
    results = poke.groupby(['Type 1']).count()
    
    new_poke = pd.concat([new_poke, results])
    print('Chunkz')
    print(new_poke)